[package]
workspace = ".."
name = "lazybox_graphics"
version = "0.1.0"
authors = ["Thomas Koehler <basta.t.k+git@gmail.com>"]

[dependencies]
gfx = "0.12"
gfx_core = "0.4"
gfx_device_gl = "0.11"
gfx_window_glutin = "0.12"
glutin = "0.6"
rusttype = "0.2"
conrod = { version = "0.39", features = ["glutin"] }
cgmath = "0.10"
image = "0.10"
quickersort = "2.0"
rayon = "0.4"

[dev_dependencies]
rand = "0.3"
lazybox_frameclock = { path = "../frameclock" }
